INSERT INTO paket (nama_paket)
values
("Anggur/Grapes PSAT Karantina"),
("Alpukat/Avocado PSAT Karantina"),
("Apel/Apple PSAT Karantina"),
("Aprikot/Apricot PSAT Karantina"),
("Beri/Berries PSAT Karantina"),
("Blackberries/Blackberries PSAT Karantina"),
("Blueberries/Blueberries PSAT Karantina"),
("Boysenberry/Boysenberry PSAT Karantina"),
("Ceri/Cherries PSAT Karantina"),
("Cranberry/Cranberry PSAT Karantina"),
("Buah Sitrus/Citrus Fruit PSAT Karantina"),
("Currant, Hitam Merah, Putih/Currant, Black, Red, White PSAT Karantina"),
("Dewberries/Dewberries PSAT Karantina"),
("Durian/Durian PSAT Karantina"),
("Gooseberry/Gooseberry PSAT Karantina"),
("Grapefruit PSAT Karantina"),
("Jeruk/Oranges PSAT Karantina"),
("Kelengkeng/Longan PSAT Karantina"),
("Kismis/Raisins PSAT Karantina"),
("Kiwi/Kiwifruit PSAT Karantina"),
("Leci/Lychee (Litchi) PSAT Karantina"),
("Jeruk Nipis/Limes PSAT Karantina"),
("Jeruk Mandarin/Mandarin PSAT Karantina"),
("Mangga/Mango PSAT Karantina"),
("Melon/Melon PSAT Karantina"),
("Melon Jingga/Cantaloupe or Rock Melon PSAT Karantina"),
("Nanas/Pineapple PSAT Karantina"),
("Nektarin/Nectarine PSAT Karantina"),
("Pepaya/Papaya PSAT Karantina"),
("Persik/Peach PSAT Karantina"),
("Persimon/Persimmon PSAT Karantina"),
("Persimon Jepang/Japanese Persimmon PSAT Karantina"),
("Pisang/Banana PSAT Karantina"),
("Pir/Pear PSAT Karantina"),
("Plum/Plum PSAT Karantina"),
("Pomelo/Shaddock or pomelos PSAT Karantina"),
("Prunes/Prunes PSAT Karantina"),
("Rasberries, Merah, Hitam/Raspberries, red, black PSAT Karantina"),
("Squash/Squash PSAT Karantina"),
("Srikaya/Custard Apple PSAT Karantina"),
("Stroberi/Strawberry PSAT Karantina"),
("Arthicokes/Arthicokes PSAT Karantina"),
("Asparagus/Asparagus PSAT Karantina"),
("Bawang Bombay/Onion PSAT Karantina"),
("Spring Onions/Spring onions PSAT Karantina"),
("Bawang Putih/Garlic PSAT Karantina"),
("Bayam/Spinach PSAT Karantina"),
("Bit/Beetroot PSAT Karantina"),
("Bit Gula/Sugar Beet PSAT Karantina"),
("Brokoli/Broccoli PSAT Karantina"),
("Bunga Kol/Cauliflower PSAT Karantina"),
("Cabai/Peppers Chili PSAT Karantina"),
("Cabai (kering)/Peppers Chili, dried PSAT Karantina"),
("Daun Bawang/Leeks PSAT Karantina"),
("Flowerhead brassicas/Flowerhead brassicas PSAT Karantina"),
("Gherkin/Gherkin PSAT Karantina"),
("Jagung manis dengan tongkolnya/Sweet corn (corn-on-the-cob) PSAT Karantina"),
("Jagung manis pipilan/Sweet corn (kernel) PSAT Karantina"),
("Jamur/Mushrooms PSAT Karantina"),
("Kentang/Potatoes PSAT Karantina"),
("Kale/Kale PSAT Karantina"),
("Kohlrabi/Kohlrabi PSAT Karantina"),
("Kubis, kepala/Cabbage, head PSAT Karantina"),
("Kubis, savoy/Cabbage, savoy PSAT Karantina"),
("Kubis Brussels/Brussels sprouts PSAT Karantina"),
("Kubis cina tipe pe-tsai/Chinnese cabbage type pe-tsai PSAT Karantina"),
("Kacang Lima/Lima bean PSAT Karantina"),
("Lobak/Radish PSAT Karantina"),
("Lobak, jepang/Radish, japanese PSAT Karantina"),
("Lobak Cina/Turnips PSAT Karantina"),
("Mentimun/Cucumber PSAT Karantina"),
("Paprika/Paprika (Sweet Pepper) PSAT Karantina"),
("Okra/Okra PSAT Karantina"),
("Selada/Lettuce PSAT Karantina"),
("Selada, daun/Lettuce, leaf PSAT Karantina"),
("Seledri/Celery PSAT Karantina"),
("Tomat/Tomato PSAT Karantina"),
("Terung/Eggplant PSAT Karantina"),
("Ubi Jalar/Sweet Potatoes PSAT Karantina"),
("Wortel/Carrot PSAT Karantina"),
("Jali-Jali/Barley PSAT Karantina"),
("Beras/Rice PSAT Karantina"),
("Beras pecah kulit/Rice, husked PSAT Karantina"),
("Beras dipoles (disosoh)/Rice, polished PSAT Karantina"),
("Gandum/Wheat PSAT Karantina"),
("Jagung/Maize PSAT Karantina"),
("Tepung Jagung/Maize Flour PSAT Karantina"),
("Oat/Oats PSAT Karantina"),
("Rye, Tepung Rye/Rye, Rye Flour PSAT Karantina"),
("Shorgum/Shorgum PSAT Karantina"),
("Kacang Almond/Almond PSAT Karantina"),
("Kacang Hazel/Hazelnuts PSAT Karantina"),
("Kacang Makadamia/Macadamia Nut PSAT Karantina"),
("Kacang Pistachios/Pistachios Nut PSAT Karantina"),
("Kacang Tanah/Peanut PSAT Karantina"),
("Pecan/Pecan PSAT Karantina"),
("Kedelai/Soybean PSAT Karantina"),
("Kacang Hijau/Mug Bean PSAT Karantina"),
("Kacang Babi/Bread Bean PSAT Karantina"),
("Kacang Otok, Tunggak, Tolo/Cowpea PSAT Karantina"),
("Kacang Kapri atau Polong/Peas PSAT Karantina"),
("Biji Kopi/Coffee Beans PSAT Karantina"),
("Lada Hitam, Putih/Pepper Balck, White PSAT Karantina"),
("Tebu/Sugar Cane PSAT Karantina"),
("The Hijau, Hitam/Tea Green, Black PSAT Karantina"),
("Kurma/Kurma PSAT Karantina"),
("Sunflower, Pumpkin, Chia Seeds PSAT Karantina")
