INSERT INTO paket (nama_paket)
values
("Anggur/Grapes PSAT OKKPD"),
("Alpukat/Avocado PSAT OKKPD"),
("Apel/Apple PSAT OKKPD"),
("Aprikot/Apricot PSAT OKKPD"),
("Beri/Gojiberry PSAT OKKPD"),
("Blackberries/Blackberries PSAT OKKPD"),
("Blueberries/Blueberries PSAT OKKPD"),
("Boysenberry/Boysenberry PSAT OKKPD"),
("Ceri/Cherries PSAT OKKPD"),
("Cranberry/Cranberry PSAT OKKPD"),
("Buah Sitrus/Citrus Fruit PSAT OKKPD"),
("Currant, Hitam Merah, Putih/Currant, Black, Red, White PSAT OKKPD"),
("Dewberries/Dewberries PSAT OKKPD"),
("Durian/Durian PSAT OKKPD"),
("Gooseberry/Gooseberry PSAT OKKPD"),
("Grapefruit PSAT OKKPD"),
("Jeruk/Oranges PSAT OKKPD"),
("Kelengkeng/Longan PSAT OKKPD"),
("Kismis/Raisins PSAT OKKPD"),
("Kiwi/Kiwifruit PSAT OKKPD"),
("Leci/Lychee (Litchi) PSAT OKKPD"),
("Jeruk Nipis/Limes PSAT OKKPD"),
("Jeruk Mandarin/Mandarin PSAT OKKPD"),
("Mangga/Mango PSAT OKKPD"),
("Melon/Melon PSAT OKKPD"),
("Melon Jingga/Cantaloupe or Rock Melon PSAT OKKPD"),
("Nanas/Pineapple PSAT OKKPD"),
("Nektarin/Nectarine PSAT OKKPD"),
("Pepaya/Papaya PSAT OKKPD"),
("Persik/Peach PSAT OKKPD"),
("Persimon/Persimmon PSAT OKKPD"),
("Persimon Jepang/Japanese Persimmon PSAT OKKPD"),
("Pisang/Banana PSAT OKKPD"),
("Pir/Pear PSAT OKKPD"),
("Plum/Plum PSAT OKKPD"),
("Pomelo/Shaddock or pomelos PSAT OKKPD"),
("Prunes/Prunes PSAT OKKPD"),
("Rasberries, Merah, Hitam/Raspberries, red, black PSAT OKKPD"),
("Squash/Squash PSAT OKKPD"),
("Srikaya/Custard Apple PSAT OKKPD"),
("Stroberi/Strawberry PSAT OKKPD"),
("Arthicokes/Arthicokes PSAT OKKPD"),
("Asparagus/Asparagus PSAT OKKPD"),
("Bawang Bombay/Onion PSAT OKKPD"),
("Spring Onions/Spring onions PSAT OKKPD"),
("Bawang Putih/Garlic PSAT OKKPD"),
("Bayam/Spinach PSAT OKKPD"),
("Bit/Beetroot PSAT OKKPD"),
("Bit Gula/Sugar Beet PSAT OKKPD"),
("Brokoli/Broccoli PSAT OKKPD"),
("Bunga Kol/Cauliflower PSAT OKKPD"),
("Cabai/Peppers Chili PSAT OKKPD"),
("Cabai (kering)/Peppers Chili, dried PSAT OKKPD"),
("Daun Bawang/Leeks PSAT OKKPD"),
("Flowerhead brassicas/Flowerhead brassicas PSAT OKKPD"),
("Gherkin/Gherkin PSAT OKKPD"),
("Jagung manis dengan tongkolnya/Sweet corn (corn-on-the-cob) PSAT OKKPD"),
("Jagung manis pipilan/Sweet corn (kernel) PSAT OKKPD"),
("Jamur/Mushrooms PSAT OKKPD"),
("Kentang/Potatoes PSAT OKKPD"),
("Kale/Kale PSAT OKKPD"),
("Kohlrabi/Kohlrabi PSAT OKKPD"),
("Kubis, kepala/Cabbage, head PSAT OKKPD"),
("Kubis, savoy/Cabbage, savoy PSAT OKKPD"),
("Kubis Brussels/Brussels sprouts PSAT OKKPD"),
("Kubis cina tipe pe-tsai/Chinnese cabbage type pe-tsai PSAT OKKPD"),
("Kacang Lima/Lima bean PSAT OKKPD"),
("Lobak/Radish PSAT OKKPD"),
("Lobak, jepang/Radish, japanese PSAT OKKPD"),
("Lobak Cina/Turnips PSAT OKKPD"),
("Mentimun/Cucumber PSAT OKKPD"),
("Paprika/Paprika (Sweet Pepper) PSAT OKKPD"),
("Okra/Okra PSAT OKKPD"),
("Selada/Lettuce PSAT OKKPD"),
("Selada, daun/Lettuce, leaf PSAT OKKPD"),
("Seledri/Celery PSAT OKKPD"),
("Tomat/Tomato PSAT OKKPD"),
("Terung/Eggplant PSAT OKKPD"),
("Ubi Jalar/Sweet Potatoes PSAT OKKPD"),
("Wortel/Carrot PSAT OKKPD"),
("Jali-Jali/Barley PSAT OKKPD"),
("Beras/Rice PSAT OKKPD"),
("Beras pecah kulit/Rice, husked PSAT OKKPD"),
("Beras dipoles (disosoh)/Rice, polished PSAT OKKPD"),
("Gandum/Wheat PSAT OKKPD"),
("Jagung/Maize PSAT OKKPD"),
("Tepung Jagung/Maize Flour PSAT OKKPD"),
("Oat/Oats PSAT OKKPD"),
("Rye, Tepung Rye/Rye, Rye Flour PSAT OKKPD"),
("Shorgum/Shorgum PSAT OKKPD"),
("Kacang Almond/Almond PSAT OKKPD"),
("Kacang Hazel/Hazelnuts PSAT OKKPD"),
("Kacang Makadamia/Macadamia Nut PSAT OKKPD"),
("Kacang Pistachios/Pistachios Nut PSAT OKKPD"),
("Kacang Tanah/Peanut PSAT OKKPD"),
("Pecan/Pecan PSAT OKKPD"),
("Kedelai/Soybean PSAT OKKPD"),
("Kacang Hijau/Mug Bean PSAT OKKPD"),
("Kacang Babi/Bread Bean PSAT OKKPD"),
("Kacang Otok, Tunggak, Tolo/Cowpea PSAT OKKPD"),
("Kacang Kapri atau Polong/Peas PSAT OKKPD"),
("Biji Kopi/Coffee Beans PSAT OKKPD"),
("Lada Hitam, Putih/Pepper Balck, White PSAT OKKPD"),
("Tebu/Sugar Cane PSAT OKKPD"),
("The Hijau, Hitam/Tea Green, Black PSAT OKKPD"),
("Kurma/Kurma PSAT OKKPD"),
("Sunflower, Pumpkin, Chia Seeds PSAT OKKPD");
